export const projects = [
  {
    title: "Github-Search",
    description: "Get detailed view of your repositories.",
    image: "/images/1.webp",
    tags: ["React", "Context", "Styled Components", "Auth0"],
    source: "https://github.com/Damislav/react-github-search-users-context",
    visit: "https://react-github-search-context.netlify.app/",
    id: 0,
  },
  {
    title: "Web Shop",
    description: "Computer shop made for algebra course",
    image: "/images/2.png",
    tags: ["HTML, CSS ,Javascript"],
    source: "https://github.com/Damislav/Ivan_Damjanovi-",
    visit: "https://damislav.github.io/Ivan_Damjanovi-/",
    id: 1,
  },
  {
    title: "Comfy-Sloth",
    description: "Buy amazing furniture for your home.",
    image: "/images/3.webp",
    tags: ["React", "Context", "Styled Components", "Auth0", "Stripe"],
    source: "https://github.com/Damislav/comfy-sloth",
    visit: "https://comfy-sloth-react-app.netlify.app/",
    id: 2,
  },
  {
    title: "Unreal Blog",
    description: "Unreal development blog.",
    image: "/images/4.webp",
    tags: ["Nextjs", "GraphQL", "SCSS", "TailwindCSS", "GraphCMS"],
    source: "https://github.com/Damislav/blog-graphql",
    visit: "https://damislav-at-games.vercel.app/",
    id: 3,
  },
];
